/*
 * generated by Xtext 2.25.0
 */
package idm.projet.portail.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import idm.projet.portail.ide.contentassist.antlr.internal.InternalTextParser;
import idm.projet.portail.services.TextGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class TextParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(TextGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, TextGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getUniversiteAccess().getAlternatives_2(), "rule__Universite__Alternatives_2");
			builder.put(grammarAccess.getEmployeAccess().getAlternatives(), "rule__Employe__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getFormationAccess().getAlternatives_21(), "rule__Formation__Alternatives_21");
			builder.put(grammarAccess.getSeanceKindAccess().getAlternatives(), "rule__SeanceKind__Alternatives");
			builder.put(grammarAccess.getUniversiteAccess().getGroup(), "rule__Universite__Group__0");
			builder.put(grammarAccess.getDepartementAccess().getGroup(), "rule__Departement__Group__0");
			builder.put(grammarAccess.getSecretaireAccess().getGroup(), "rule__Secretaire__Group__0");
			builder.put(grammarAccess.getIntervenantAccess().getGroup(), "rule__Intervenant__Group__0");
			builder.put(grammarAccess.getIntervenantAccess().getGroup_19(), "rule__Intervenant__Group_19__0");
			builder.put(grammarAccess.getIntervenantAccess().getGroup_19_3(), "rule__Intervenant__Group_19_3__0");
			builder.put(grammarAccess.getIntervenantAccess().getGroup_20(), "rule__Intervenant__Group_20__0");
			builder.put(grammarAccess.getIntervenantAccess().getGroup_20_3(), "rule__Intervenant__Group_20_3__0");
			builder.put(grammarAccess.getIntervenantAccess().getGroup_21(), "rule__Intervenant__Group_21__0");
			builder.put(grammarAccess.getIntervenantAccess().getGroup_22(), "rule__Intervenant__Group_22__0");
			builder.put(grammarAccess.getFormationAccess().getGroup(), "rule__Formation__Group__0");
			builder.put(grammarAccess.getFormationAccess().getGroup_14(), "rule__Formation__Group_14__0");
			builder.put(grammarAccess.getFormationAccess().getGroup_19(), "rule__Formation__Group_19__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getParcoursAccess().getGroup(), "rule__Parcours__Group__0");
			builder.put(grammarAccess.getParcoursAccess().getGroup_18(), "rule__Parcours__Group_18__0");
			builder.put(grammarAccess.getUEAccess().getGroup(), "rule__UE__Group__0");
			builder.put(grammarAccess.getUEAccess().getGroup_46(), "rule__UE__Group_46__0");
			builder.put(grammarAccess.getUEAccess().getGroup_51(), "rule__UE__Group_51__0");
			builder.put(grammarAccess.getSemestreAccess().getGroup(), "rule__Semestre__Group__0");
			builder.put(grammarAccess.getSemestreAccess().getGroup_11(), "rule__Semestre__Group_11__0");
			builder.put(grammarAccess.getSemestreAccess().getGroup_11_3(), "rule__Semestre__Group_11_3__0");
			builder.put(grammarAccess.getSemestreAccess().getGroup_15(), "rule__Semestre__Group_15__0");
			builder.put(grammarAccess.getEDateAccess().getGroup(), "rule__EDate__Group__0");
			builder.put(grammarAccess.getSeanceAccess().getGroup(), "rule__Seance__Group__0");
			builder.put(grammarAccess.getSeanceAccess().getGroup_23(), "rule__Seance__Group_23__0");
			builder.put(grammarAccess.getSeanceAccess().getGroup_23_3(), "rule__Seance__Group_23_3__0");
			builder.put(grammarAccess.getRessourceAccess().getGroup(), "rule__Ressource__Group__0");
			builder.put(grammarAccess.getUniversiteAccess().getNameAssignment_1(), "rule__Universite__NameAssignment_1");
			builder.put(grammarAccess.getUniversiteAccess().getDepartementsAssignment_2_0(), "rule__Universite__DepartementsAssignment_2_0");
			builder.put(grammarAccess.getUniversiteAccess().getEmployesAssignment_2_1(), "rule__Universite__EmployesAssignment_2_1");
			builder.put(grammarAccess.getDepartementAccess().getNameAssignment_1(), "rule__Departement__NameAssignment_1");
			builder.put(grammarAccess.getDepartementAccess().getDescriptionAssignment_5(), "rule__Departement__DescriptionAssignment_5");
			builder.put(grammarAccess.getDepartementAccess().getResponsableDepartementAssignment_9(), "rule__Departement__ResponsableDepartementAssignment_9");
			builder.put(grammarAccess.getDepartementAccess().getFormationsAssignment_11(), "rule__Departement__FormationsAssignment_11");
			builder.put(grammarAccess.getDepartementAccess().getFormationsAssignment_12(), "rule__Departement__FormationsAssignment_12");
			builder.put(grammarAccess.getSecretaireAccess().getNameAssignment_1(), "rule__Secretaire__NameAssignment_1");
			builder.put(grammarAccess.getSecretaireAccess().getTelephoneAssignment_5(), "rule__Secretaire__TelephoneAssignment_5");
			builder.put(grammarAccess.getSecretaireAccess().getBureauAssignment_9(), "rule__Secretaire__BureauAssignment_9");
			builder.put(grammarAccess.getSecretaireAccess().getMailAssignment_13(), "rule__Secretaire__MailAssignment_13");
			builder.put(grammarAccess.getSecretaireAccess().getFormationAssignment_17(), "rule__Secretaire__FormationAssignment_17");
			builder.put(grammarAccess.getIntervenantAccess().getNameAssignment_1(), "rule__Intervenant__NameAssignment_1");
			builder.put(grammarAccess.getIntervenantAccess().getTelephoneAssignment_5(), "rule__Intervenant__TelephoneAssignment_5");
			builder.put(grammarAccess.getIntervenantAccess().getBureauAssignment_9(), "rule__Intervenant__BureauAssignment_9");
			builder.put(grammarAccess.getIntervenantAccess().getMailAssignment_13(), "rule__Intervenant__MailAssignment_13");
			builder.put(grammarAccess.getIntervenantAccess().getSpecialiteAssignment_17(), "rule__Intervenant__SpecialiteAssignment_17");
			builder.put(grammarAccess.getIntervenantAccess().getUesIntervenantAssignment_19_2(), "rule__Intervenant__UesIntervenantAssignment_19_2");
			builder.put(grammarAccess.getIntervenantAccess().getUesIntervenantAssignment_19_3_1(), "rule__Intervenant__UesIntervenantAssignment_19_3_1");
			builder.put(grammarAccess.getIntervenantAccess().getUesResponsableAssignment_20_2(), "rule__Intervenant__UesResponsableAssignment_20_2");
			builder.put(grammarAccess.getIntervenantAccess().getUesResponsableAssignment_20_3_1(), "rule__Intervenant__UesResponsableAssignment_20_3_1");
			builder.put(grammarAccess.getIntervenantAccess().getResponsableFormationAssignment_21_2(), "rule__Intervenant__ResponsableFormationAssignment_21_2");
			builder.put(grammarAccess.getIntervenantAccess().getResponsableParcoursAssignment_22_2(), "rule__Intervenant__ResponsableParcoursAssignment_22_2");
			builder.put(grammarAccess.getFormationAccess().getNameAssignment_1(), "rule__Formation__NameAssignment_1");
			builder.put(grammarAccess.getFormationAccess().getDescriptionAssignment_5(), "rule__Formation__DescriptionAssignment_5");
			builder.put(grammarAccess.getFormationAccess().getCreditAssignment_9(), "rule__Formation__CreditAssignment_9");
			builder.put(grammarAccess.getFormationAccess().getSecretairesAssignment_13(), "rule__Formation__SecretairesAssignment_13");
			builder.put(grammarAccess.getFormationAccess().getSecretairesAssignment_14_1(), "rule__Formation__SecretairesAssignment_14_1");
			builder.put(grammarAccess.getFormationAccess().getResponsablesFormationAssignment_18(), "rule__Formation__ResponsablesFormationAssignment_18");
			builder.put(grammarAccess.getFormationAccess().getResponsablesFormationAssignment_19_1(), "rule__Formation__ResponsablesFormationAssignment_19_1");
			builder.put(grammarAccess.getFormationAccess().getUesAssignment_21_0(), "rule__Formation__UesAssignment_21_0");
			builder.put(grammarAccess.getFormationAccess().getParcoursAssignment_21_1(), "rule__Formation__ParcoursAssignment_21_1");
			builder.put(grammarAccess.getParcoursAccess().getNameAssignment_1(), "rule__Parcours__NameAssignment_1");
			builder.put(grammarAccess.getParcoursAccess().getDescriptionAssignment_5(), "rule__Parcours__DescriptionAssignment_5");
			builder.put(grammarAccess.getParcoursAccess().getCompetenceAssignment_9(), "rule__Parcours__CompetenceAssignment_9");
			builder.put(grammarAccess.getParcoursAccess().getDeboucheAssignment_13(), "rule__Parcours__DeboucheAssignment_13");
			builder.put(grammarAccess.getParcoursAccess().getResponsableParcoursAssignment_17(), "rule__Parcours__ResponsableParcoursAssignment_17");
			builder.put(grammarAccess.getParcoursAccess().getResponsableParcoursAssignment_18_1(), "rule__Parcours__ResponsableParcoursAssignment_18_1");
			builder.put(grammarAccess.getParcoursAccess().getSemestresAssignment_20(), "rule__Parcours__SemestresAssignment_20");
			builder.put(grammarAccess.getParcoursAccess().getSemestresAssignment_21(), "rule__Parcours__SemestresAssignment_21");
			builder.put(grammarAccess.getUEAccess().getNameAssignment_1(), "rule__UE__NameAssignment_1");
			builder.put(grammarAccess.getUEAccess().getDescriptionAssignment_5(), "rule__UE__DescriptionAssignment_5");
			builder.put(grammarAccess.getUEAccess().getObjectifAssignment_9(), "rule__UE__ObjectifAssignment_9");
			builder.put(grammarAccess.getUEAccess().getCompetenceAssignment_13(), "rule__UE__CompetenceAssignment_13");
			builder.put(grammarAccess.getUEAccess().getEvaluationAssignment_17(), "rule__UE__EvaluationAssignment_17");
			builder.put(grammarAccess.getUEAccess().getProgrammeAssignment_21(), "rule__UE__ProgrammeAssignment_21");
			builder.put(grammarAccess.getUEAccess().getTypeEnseignementAssignment_25(), "rule__UE__TypeEnseignementAssignment_25");
			builder.put(grammarAccess.getUEAccess().getCreditAssignment_29(), "rule__UE__CreditAssignment_29");
			builder.put(grammarAccess.getUEAccess().getHeureCMAssignment_33(), "rule__UE__HeureCMAssignment_33");
			builder.put(grammarAccess.getUEAccess().getHeureTDAssignment_37(), "rule__UE__HeureTDAssignment_37");
			builder.put(grammarAccess.getUEAccess().getHeureTPAssignment_41(), "rule__UE__HeureTPAssignment_41");
			builder.put(grammarAccess.getUEAccess().getResponsablesAssignment_45(), "rule__UE__ResponsablesAssignment_45");
			builder.put(grammarAccess.getUEAccess().getResponsablesAssignment_46_1(), "rule__UE__ResponsablesAssignment_46_1");
			builder.put(grammarAccess.getUEAccess().getIntervenantsAssignment_50(), "rule__UE__IntervenantsAssignment_50");
			builder.put(grammarAccess.getUEAccess().getIntervenantsAssignment_51_1(), "rule__UE__IntervenantsAssignment_51_1");
			builder.put(grammarAccess.getUEAccess().getSeancesAssignment_53(), "rule__UE__SeancesAssignment_53");
			builder.put(grammarAccess.getUEAccess().getSeancesAssignment_54(), "rule__UE__SeancesAssignment_54");
			builder.put(grammarAccess.getSemestreAccess().getNameAssignment_1(), "rule__Semestre__NameAssignment_1");
			builder.put(grammarAccess.getSemestreAccess().getDateDebutAssignment_5(), "rule__Semestre__DateDebutAssignment_5");
			builder.put(grammarAccess.getSemestreAccess().getDateFinAssignment_9(), "rule__Semestre__DateFinAssignment_9");
			builder.put(grammarAccess.getSemestreAccess().getUeFacultativesAssignment_11_2(), "rule__Semestre__UeFacultativesAssignment_11_2");
			builder.put(grammarAccess.getSemestreAccess().getUeFacultativesAssignment_11_3_1(), "rule__Semestre__UeFacultativesAssignment_11_3_1");
			builder.put(grammarAccess.getSemestreAccess().getUeObligatoiresAssignment_14(), "rule__Semestre__UeObligatoiresAssignment_14");
			builder.put(grammarAccess.getSemestreAccess().getUeObligatoiresAssignment_15_1(), "rule__Semestre__UeObligatoiresAssignment_15_1");
			builder.put(grammarAccess.getSeanceAccess().getNameAssignment_1(), "rule__Seance__NameAssignment_1");
			builder.put(grammarAccess.getSeanceAccess().getDateAssignment_5(), "rule__Seance__DateAssignment_5");
			builder.put(grammarAccess.getSeanceAccess().getHeureDebutAssignment_9(), "rule__Seance__HeureDebutAssignment_9");
			builder.put(grammarAccess.getSeanceAccess().getHeureFinAssignment_13(), "rule__Seance__HeureFinAssignment_13");
			builder.put(grammarAccess.getSeanceAccess().getDescriptionAssignment_17(), "rule__Seance__DescriptionAssignment_17");
			builder.put(grammarAccess.getSeanceAccess().getKindAssignment_21(), "rule__Seance__KindAssignment_21");
			builder.put(grammarAccess.getSeanceAccess().getRessourcesAssignment_23_2(), "rule__Seance__RessourcesAssignment_23_2");
			builder.put(grammarAccess.getSeanceAccess().getRessourcesAssignment_23_3_1(), "rule__Seance__RessourcesAssignment_23_3_1");
			builder.put(grammarAccess.getRessourceAccess().getNameAssignment_1(), "rule__Ressource__NameAssignment_1");
			builder.put(grammarAccess.getRessourceAccess().getLienAssignment_5(), "rule__Ressource__LienAssignment_5");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private TextGrammarAccess grammarAccess;

	@Override
	protected InternalTextParser createParser() {
		InternalTextParser result = new InternalTextParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public TextGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TextGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
