/*
 * generated by Xtext 2.25.0
 */
package idm.projet.portail;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TextStandaloneSetup extends TextStandaloneSetupGenerated {

	public static void doSetup() {
		new TextStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
