/*
 * generated by Xtext 2.25.0
 */
package idm.projet.portail.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTextScopeProvider extends DelegatingScopeProvider {
}
