/*
 * generated by Xtext 2.25.0
 */
package idm.projet.portail.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import idm.projet.portail.TextRuntimeModule;
import idm.projet.portail.TextStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class TextIdeSetup extends TextStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TextRuntimeModule(), new TextIdeModule()));
	}
	
}
