/*
 * generated by Xtext 2.25.0
 */
package idm.projet.portail.ui.tests;

import com.google.inject.Injector;
import idm.projet.portail.text.ui.internal.TextActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class TextUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TextActivator.getInstance().getInjector("idm.projet.portail.Text");
	}

}
