/*
 * generated by Xtext 2.25.0
 */
package idm.projet.portail.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TextUiModule extends AbstractTextUiModule {

	public TextUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
