/*
 * generated by Xtext 2.25.0
 */
package idm.projet.portail.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TextAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("idm/projet/portail/parser/antlr/internal/InternalText.tokens");
	}
}
