/*
 * generated by Xtext 2.25.0
 */
package idm.projet.portail.parser.antlr;

import com.google.inject.Inject;
import idm.projet.portail.parser.antlr.internal.InternalTextParser;
import idm.projet.portail.services.TextGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class TextParser extends AbstractAntlrParser {

	@Inject
	private TextGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTextParser createParser(XtextTokenStream stream) {
		return new InternalTextParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Universite";
	}

	public TextGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TextGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
