/*
 * generated by Xtext 2.25.0
 */
package idm.projet.portail.ui;

import com.google.inject.Injector;
import idm.projet.portail.text.ui.internal.TextActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TextExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(TextActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		TextActivator activator = TextActivator.getInstance();
		return activator != null ? activator.getInjector(TextActivator.IDM_PROJET_PORTAIL_TEXT) : null;
	}

}
